keys:
  - &desktop01 age1ex3lj86lfptdvk8lc3gfx20cn56qcgwsyvcnajpxh29uktqw8ggss83skh
  - &server01 age1qjat66dkywzn7pkdlf9q09huq7p9rpwcysgjkc36sauuxr5j2qzsm2p4zx
creation_rules:
  - path_reges: secrets/shared.yaml$
    key_groups:
      - age: [*desktop01, *server01]
  - path_reges: secrets/server01.yaml$
    key_groups:
      - age: [*server01]
