- description: ""
  alias: living_room_light_remote
  use_blueprint:
    path: jhol-byte/Ikea_bilresa_scroll_wheel.yaml
    input:
      scroll_wheel_target_ch1:
        - light.kajplats_e26_ws_globe_1100lm
      scroll_wheel_target_ch2:
        - light.kajplats_e26_cws_globe_1100lm
      click_action_ch1:
        - action: light.toggle
          metadata: {}
          target:
            entity_id: light.kajplats_e26_ws_globe_1100lm
          data: {}
      click_action_ch2:
        - action: light.toggle
          metadata: {}
          target:
            entity_id: light.kajplats_e26_cws_globe_1100lm
          data: {}
      double_click_action_ch1: &double_click_both
        - choose:
            - conditions:
                - condition: or
                  conditions:
                    - condition: state
                      entity_id: light.kajplats_e26_ws_globe_1100lm
                      state: "off"
                    - condition: state
                      entity_id: light.kajplats_e26_cws_globe_1100lm
                      state: "off"
              sequence:
                - action: light.turn_on
                  target:
                    entity_id:
                      - light.kajplats_e26_ws_globe_1100lm
                      - light.kajplats_e26_cws_globe_1100lm
            - conditions:
                - condition: state
                  entity_id: light.kajplats_e26_ws_globe_1100lm
                  state: "on"
                - condition: state
                  entity_id: light.kajplats_e26_cws_globe_1100lm
                  state: "on"
              sequence:
                - action: light.turn_off
                  target:
                    entity_id:
                      - light.kajplats_e26_ws_globe_1100lm
                      - light.kajplats_e26_cws_globe_1100lm
      double_click_action_ch2: *double_click_both
